### ISSUE TITLE
Is it possible to access service metrics as Cloud Foundry space developer

### ISSUE THREAD

**Issue by wolfoo2931** [pivotal-cf/docs-service-metrics#3]
.. or is this feature intended to be used by the platform operator?

**Comment by wolfoo2931** [comment]
Regarding the statement "You can configure Doppler to forward the metrics to a third party application such as Papertrail or to the Loggregator Traffic Controller."

It would be nice to know who is "You" and how to configure this.

**Comment by vikafed** [comment]
@wolfoo2931 PCF services can be integrated with Loggregator, which enables you to send your service logs and metrics to the Loggregator Firehose. The Logs, Metrics, and Nozzles doc https://docs.pivotal.io/tiledev/nozzle.html explains how to integrate PCF services with Loggregator by writing to and reading from its Firehose endpoint. Also, you can find information about how to forward app and component logs and metrics to an external service (instead of routing them to the Firehose) at http://docs.pivotal.io/pivotalcf/1-11/loggregator/log-ops-guide.html#syslog-forward. Hope this helps.

@craigfurman, do you have any thoughts on this? Thanks!

**Comment by avade** [comment]
@wolfoo2931 as CF restricts access to the firehose to admin users, this feature is targeted at platform operators.

In the future if loggregator makes it possible for other users to access the firehose for apps + services, then we will support this in service metrics.
